### PR TITLE
composer. use PSR-4 over deprecated PSR-0

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks for bringing attention to this. As the main feature, PSR-4 supports shorter directory structures, so to really migrate to PSR-4, the package name should be removed from src...

**Comment by TomasVotruba** [comment]
Should I move the code then,

**Comment by lastzero** [comment]
Let me do it for all of my PHP projects when I find the time (consistency means less complexity). Since PSR-0 support is not going to be removed from composer any time soon, this has a very low priority on my todo list compared to other things but I'll do it eventually. Don't think it makes a difference for the users of my libraries since composer handles class loading transparently.

**Comment by TomasVotruba** [comment]
Sure, fine with me.

**Pull request closed without merging**
