### PR TITLE
Make use of PHP 7 strict_types

### PR DESCRIPTION
**Pull request by TomasVotruba**
...since this package uses PHP 7 as min version.

Let me know if you'd like it placed somewhere else.

Personally I prefer less attention to it, since it's always the same and everywhere (like `<?php`):

```php
<?php define(strict_types=1);

namespace ...
```

### CODE REVIEW

**Comment by lastzero** [comment]
For strict mode, I go with Benjamin: http://www.whitewashing.de/2015/02/10/a_case_for_weak_type_hints_only_in_php7.html

The key aspect here is, that developers have to “replicate weak type hinting” by manually casting everywhere, which is not really productive (see e64cdea). This library focuses on productivity. Copying everything from Java is not what made PHP strong and efficient as a programming language. If people want Java, that can use Java.

**Comment by TomasVotruba** [comment]
I found this very productive, because it prevents false positives. I can rely on package it does only what is supposed to do.

Will `str_pad(10, 1)` return a number or not?

Also this post is from time, when PHP 7 was not even out yet. Now it's 7.1.1 with nullable types. And focuses mostly on application, not packages. 

Adding strict types to my 20+ packages helped me to discover many assumptions that just failed.

Is Java features the reason not to use PHP features?

**Comment by TomasVotruba** [comment]
Fine with me, just for inspiration.

**Comment by lastzero** [comment]
It's certainly good to get inspiration. Thank you for that :)

When it comes to nullable types, I think that's a step backwards, since mixed result types force developers to spam their code with if...else statements all over the place. You'll certainly find a chapter about that in Uncle Bob's "Clean Code".

**Comment by TomasVotruba** [comment]
What I look forward is possibility of more types: `string|int $value`. What do you think of that?

I read "Clean Code", but it's to historical and Java. Also it lead me to false principal, that writing clean code is hard.

What I enjoyed much more and PHP related is: https://leanpub.com/principles-of-package-design

10 years younger, PHP and right to the point :)

**Comment by lastzero** [comment]
IMHO "Clean Code" is a good read and applies for all languages even though the examples are in Java. Saying "I don't have to write clean code since I'm using language X" is really a weak excuse. I don't think it's hard, actually it makes everything easier. My test tools are a great example how you can combine clean code with productivity. Not everything has to be complex and complicated. I'll let you know, if I find a recent book that fits into the same category and that I can recommend.

**Comment by TomasVotruba** [comment]
> "I don't have to write clean code since I'm using language X"

It is. Who said that to you?


There are better books now that explains in "native" language with less words and are more clear. So it's spreading more and is really enjoyable. 

Doesn't have to fit the category. Just any book around PHP ecosystem you read and liked recently (+-5 years).

**Pull request closed without merging**
